using namespace System.Collections.Generic
using module    ".\DefineLoginSheet.PSM1"
####################################################################################
class LoginSheet : System.Collections.Generic.List[DefineLoginSheet] {}
####################################################################################
enum DefFiles 
{
  TetaTermMacro
  Common
  PASDAT
  DAT
  LOG
}
####################################################################################
